// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtmKk8mu3MGPKlnCWkwIODm1yxKlO2_xU',
    appId: '1:620194372699:web:d9c90536e05831ed66b37e',
    messagingSenderId: '620194372699',
    projectId: 'chatapp-a2b6c',
    authDomain: 'chatapp-a2b6c.firebaseapp.com',
    storageBucket: 'chatapp-a2b6c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Ka5vzBASeoUeR96SGg-x2iSip4tTqAk',
    appId: '1:620194372699:android:14fd1fc2b05c6a6b66b37e',
    messagingSenderId: '620194372699',
    projectId: 'chatapp-a2b6c',
    storageBucket: 'chatapp-a2b6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUrrOaYz3DaUFO4y19FDo6maY49DIxXLA',
    appId: '1:620194372699:ios:01ef5665a7a4abe066b37e',
    messagingSenderId: '620194372699',
    projectId: 'chatapp-a2b6c',
    storageBucket: 'chatapp-a2b6c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUrrOaYz3DaUFO4y19FDo6maY49DIxXLA',
    appId: '1:620194372699:ios:94b96731b15e06a266b37e',
    messagingSenderId: '620194372699',
    projectId: 'chatapp-a2b6c',
    storageBucket: 'chatapp-a2b6c.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
